### ISSUE TITLE
Edit HTML file use a lot of memory

### ISSUE THREAD

**Issue by Mte90** [roxma/nvim-yarp#13]
![screenshot_20180207_231256](https://user-images.githubusercontent.com/403283/35944420-9ca82dd6-0c5c-11e8-94fd-9ed6a36a8e00.png)

I discovered that when I use deoplete on VIM I have a lot of usage of memory when I edit an HTML file.
There is a way to debug this issue?

**Comment by Shougo** [comment]
Please use the latest version of deoplete.

**Comment by Mte90** [comment]
Sorry seems that updating deoplete fixed everything (I updated yesterday but seems there was other updates)!

**Comment by Shougo** [comment]
I have many commited recently :-)
