### ISSUE TITLE
[ncm2_core@yarp] ValueError: request got unsupported keyword argument(s): async_

### ISSUE THREAD

**Issue by huangyingw** [roxma/nvim-yarp#21]
Hi, when I launch nvim, I got following error in status line:
[ncm2_core@yarp] ValueError: request got unsupported keyword argument(s): async_

I already did these test inside nvim.
:echo has("nvim-0.2.2") prints 1.
:echo has("python3") prints 1

**Comment by roxma** [comment]
Try something like `pip3 install --upgrade neovim`

**Comment by huangyingw** [comment]
@roxma thanks a lot, this fix.

**Comment by neur1n** [comment]
I have upgraded `neovim`, but the error is still there. Does the version of Python matter? I was using the built-in 3.5.2 Python in Ubuntu 16.04 to compile vim.

**Comment by huangyingw** [comment]
@roxma , hi, this issue recur, I have run
pip3 install --upgrade neovim
but this time, no luck

my nvim version:
NVIM v0.3.2-dev

and checkhealth result didn't say anything about python..

**Comment by huangyingw** [comment]
looks like this help:
pip3 uninstall -y neovim pynvim
pip3 install pynvim
