### ISSUE TITLE
Job is dead error comes up every launch

### ISSUE THREAD

**Issue by Kyle-Thompson** [roxma/nvim-yarp#24]
Every time I launch neovim I'm given the following error
`[ncm2_core@yarp] Job is dead. cmd=['python3', '-u', '/.../pythonx/yarp.py', '/tmp/nvimL5FRdr/0', 2, 'ncm2_core']`. What can I do about this?

**Comment by Kyle-Thompson** [comment]
This was due to me not having installed neovim with pip. I had done so with pip3 explicitly but apparently installing with pip was needed. I'm an idiot.

**Comment by megalithic** [comment]
@Kyle-Thompson: odd, i have neovim installed via pip and pip3, and still getting this. Any details of exactly what you did?

**Comment by viniarck** [comment]
@megalithic try removing completely from your system with `pip3 uninstall neovim` and `sudo pip3 uninstall neovim`. Upgrade to the latest version, and install user only, `pip3 install neovim --user`, perform a `:checkhealth` after starting neovim.

**Comment by hiphamster** [comment]
I'm having a similar error. I have followed suggestion to completely uninstall and reinstall neovim, I'm on mac, tried using macports as well as pyenv / virtualenv, but the error persists.

**Comment by thefallenidealist** [comment]
I am having same error on FreeBSD. Uninstalling all pip2 neovim/pynvim modules and reinstalling all pip3 modules didn't help.
But on my system, root's nvim works as expected.
user:

```
## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.6.8
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.
```

root:
```
## Python 2 provider (optional)
- WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
- ERROR: Python provider error:
  - ADVICE:
	- provider/pythonx: Could not load Python 2:
		/usr/local/bin/python2 does not have the "neovim" module. :help provider-python
		/usr/local/bin/python2.7 does not have the "neovim" module. :help provider-python
		python2.6 not found in search path or not executable.
		/usr/local/bin/python does not have the "neovim" module. :help provider-python
- INFO: Executable: Not found

## Python 3 provider (optional)
- INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
- INFO: Executable: /usr/local/bin/python3
- INFO: Python version: 3.6.8
- INFO: pynvim version: 0.3.1 (outdated; from ~/.local/lib/python3.6/site-packages/neovim)
- WARNING: Latest pynvim is NOT installed: 0.3.2
```

Both user and root are using the same config (ln -s /home/user/... /root/...) but python modules are in separate dirs (~/.local).

**Comment by arizonatribe** [comment]
Honestly why does it even matter to install through Pip vs through Homebrew? That smells like brittle code to me.

**Comment by roxma** [comment]
@[thefallenidealist](/thefallenidealist) The job is dead message prints the full command startting the job. You could execute the job manually in another terminal and see how it goes.

**Comment by hiphamster** [comment]
It doesn't exactly. Most of the command doesn't fit (gets truncated), and I don't see it when i enable logging.

**Comment by roxma** [comment]
@hiphamster  Unfortunately It's hard to debug in this case.

This is different issue than the one posted by [Kyle-Thompson](/Kyle-Thompson), you should open a new  issue. And maybe a docker image for reproducing the issue, since there's no enough debugging information from your describtion.

**Comment by thefallenidealist** [comment]
> @[thefallenidealist](/thefallenidealist) The job is dead message prints the full command startting the job. You could execute the job manually in another terminal and see how it goes.

Tried that a few days ago and that worked. But not inside nvim. Anyway, rebooted machine and works as expected.
Updated root's pynvim and plugins and it is still working.
I'll try tomorrow on Win10 machine, I think there were also same error messages.

**Comment by BinJu** [comment]
I tried this with the nvim installed by brew on Mac OSX.
The command I tried the so the debug log(I linked `vim` to `nvim`):
```bash
vim -V9myVim.log
```
I can see the exact error is the module `neovim` does not exist.
I tried install the module manually, it got failed due to the `ssl` issue.  As some one suggested I ran the command to reinstall python:
```bash
brew reinstall python
```
then 
```bash
sudo pip3 install --upgrade neovim
```
after that reopen `nvim`, the error is gone. Hope this could help!

**Comment by casusbelli** [comment]
> ```shell
> brew reinstall python
> ```
> 
> then
> 
> ```shell
> sudo pip3 install --upgrade neovim
> ```
> 
> after that reopen `nvim`, the error is gone. Hope this could help!

Seems the python re-install is the key here. I just ran the brew reinstall command and afterwards tried a:

```shell
brew upgrade nvim
```
the latter did not do any changes because nvim was up to date. But still the issue is gone for me now, the only perceivable change being the python reinstallation.

**Comment by HLevering** [comment]
I had the same issue and followed the suggestion of @roxma . Executing the command directly in terminal showed:
...
ModuleNotFoundError: No module named 'jedi'
...
So I did a `pip install jedi` and it worked. Maybe this is helpful to others

**Comment by nbyouk** [comment]
After installing nvim via pip as per the comments above, I was still getting the error. I had to specify the path to my python installation in ~/.config/nvim/init.vim:

let g:python3_host_prog = '/path/to/bin/python3'
let g:python_host_prog='/path/to/bin/python2'

This solved the issue, hope it helps.

**Comment by antmachine** [comment]
I had same issue. Checking which pythons were executable
```
which python2
=> /usr/local/bin/python2
which python3
=>  /usr/bin/python3
```
It looks like python3 was pointing to MacOS python. After running `brew reinstall python` I got the correct path and issue resolved.
```
which python3
=> /usr/local/bin/python3
```

**Comment by lhagchung** [comment]
> I tried this with the nvim installed by brew on Mac OSX.
> The command I tried the so the debug log(I linked `vim` to `nvim`):
> 
> ```shell
> vim -V9myVim.log
> ```
> 
> I can see the exact error is the module `neovim` does not exist.
> I tried install the module manually, it got failed due to the `ssl` issue. As some one suggested I ran the command to reinstall python:
> 
> ```shell
> brew reinstall python
> ```
> 
> then
> 
> ```shell
> sudo pip3 install --upgrade neovim
> ```
> 
> after that reopen `nvim`, the error is gone. Hope this could help!

everyone this is helping

**Comment by rfaridi** [comment]
In my arch linux system, all I had to do is install/update the python-neovim package. No "pip install" was required.

**Comment by dobrydev** [comment]
> I tried this with the nvim installed by brew on Mac OSX.
> The command I tried the so the debug log(I linked `vim` to `nvim`):
> 
> ```shell
> vim -V9myVim.log
> ```
> 
> I can see the exact error is the module `neovim` does not exist.
> I tried install the module manually, it got failed due to the `ssl` issue. As some one suggested I ran the command to reinstall python:
> 
> ```shell
> brew reinstall python
> ```
> 
> then
> 
> ```shell
> sudo pip3 install --upgrade neovim
> ```
> 
> after that reopen `nvim`, the error is gone. Hope this could help!

Work for me. Thanks!!

**Comment by ademarj** [comment]
@Esternome tks

`brew reinstall python` && `sudo pip3 install --upgrade neovim `

It's was enough 👍

**Comment by c1au6i0** [comment]
In my case  reinstalling python  (in CentOs), pointing to the right python3, or upgrading neovim did not solve the problem. The pythonx folder contains only the `yarp.py` and no `neovim.api`. I installed `neovim` with `miniconda`.

**Comment by cassiotbatista** [comment]
> In my arch linux system, all I had to do is install/update the python-neovim package. No "pip install" was required.

Same for me: `sudo apt-get install python3-neovim` did the job :)

**Comment by kswelder** [comment]
> @megalithic try removing completely from your system with `pip3 uninstall neovim` and `sudo pip3 uninstall neovim`. Upgrade to the latest version, and install user only, `pip3 install neovim --user`, perform a `:checkhealth` after starting neovim.

thx, solve my problem in Windows.
I tryng install ncm2 plugin I was not successful because this conflict, but I reinstalled neovim with pip solve my problem.
