### ISSUE TITLE
yarp init fails

### ISSUE THREAD

**Issue by vbrinnel** [roxma/nvim-yarp#32]
Hi, 

starting macvim in verbose mode shows this error: 

<img width="982" alt="Screen Shot 2019-10-10 at 17 30 31" src="https://user-images.githubusercontent.com/17532220/66583699-1ca07900-eb84-11e9-8486-ff51fdb735da.png">

The path to yarp.py (third cmd argument) is incorrect (^@ character and duplication)

Manually replacing s:script with the correct PATH solves the issue (deoplete works perfectly thereafter)

<img width="648" alt="Screen Shot 2019-10-10 at 17 35 07" src="https://user-images.githubusercontent.com/17532220/66583977-946ea380-eb84-11e9-8dae-5581f0cbde4e.png">

cheers

Using the latest master branch.
Python version: 3.7.4 
Macvim version: 8.1.1722 (157)

**Comment by Shougo** [comment]
@vbrinnel I get the reason.  Please test #33.

**Comment by vbrinnel** [comment]
I confirm #33 fixes the issue. 
Thanks!
