### ISSUE TITLE
Neovim hangs

### ISSUE THREAD

**Issue by sassanh** [roxma/nvim-yarp#35]
Sometimes neovim hangs, when I kill it in another terminal and get back to the Neovim terminal to run it again I see it's not existed completely, I see this message:

```
[ncm2_path@yarp] Job is dead. cmd=['/usr/bin/python3', '-u', '/home/sassan/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py', '/tmp/nvim6AMiMt/0', 4, 'ncm2_path'][ncm2_bufword@yarp] Job is dead. cmd=['/usr/bin/python3', '-u', '/home/sassan/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py', '/tmp/nvim6AMiMt/0', 3, 'ncm2_bufword'][ncm2_tern@yarp] Job is dead. cmd=['/usr/bin/python3', '-u', '/home/sassan/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py', '/tmp/nvim6AMiMt/0', 8, 'ncm2_tern'][ncm2_look@yarp] Job is dead. cmd=['/usr/bin/python3', '-u', '/home/sassan/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py', '/tmp/nvim6AMiMt/0', 6, 'ncm2_look'][ncm2_core@yarp] Job is dead. cmd=['/usr/bin/python3', '-u', '/home/sassan/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py', '/tmp/nvim6AMiMt/0', 2, 'ncm2_core'][ncm2_gtags@yarp] Job is dead. cmd=['/usr/bin/python3', '-u', '/home/sassan/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py', '/tmp/nvim6AMiMt/0', 5, 'ncm2_gtags'][ncm2_jedi@yarp] Job is dead. cmd=['/usr/bin/python3', '-u', '/home/sassan/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py', '/tmp/nvim6AMiMt/0', 7, 'ncm2_jedi']
```

If I hit <kbd>ctrl</kbd> + <kbd>c</kbd> it'll exit (or if I kill vim with signal 9).

It happens very rarely, I usually have more than 5 instances of Neovim open for several days, and it happens for one of them after few days. But it happens at more than once per week.

Do you think it's related to nvim-yarp?

**Comment by roxma** [comment]
It's probably related to https://github.com/ncm2/ncm2-jedi/issues/1

**Comment by sassanh** [comment]
I'm not using old Python, `/usr/bin/python3` on my machine (as reported in error to be the Python in used for this plugin) is Python 3.7.5rc1

**Comment by lukelbd** [comment]
Came across this issue in vim 8.X. I get very high CPU usage and vim freezes, have to force quite the python process and the resulting error message is the same. Everything is updated to the latest version with vim-plug `:PlugUpdate`.

It happens with similar frequency while editing files (or maybe a little more often... like once per day).

**Comment by Shougo** [comment]
What do you use the plugins?

**Comment by lukelbd** [comment]
Below is the output of `:PlugStatus` (includes `deoplete.nvim`, `jedi-vim`, `deoplete-jedi`, `nvim-yarp`).

<details>

```
- neco-vim: OK
- vim-textobj-line: OK
- vim-hug-neovim-rpc: OK
- vim-tmux: OK
- applescript.vim: OK
- deoplete-jedi: OK
- tcomment_vim: OK
- neco-syntax: OK
- vim-autoformat: OK
- braceless.vim: OK
- tagbar: OK
- vim-easy-align: OK
- undotree: OK
- vim-cython: OK
- vim-markdown: OK
- vim-eunuch: OK
- vim-matchup: OK
- vim-textobj-indent: OK
- vim-autopep8: OK
- jupytext.vim: OK
- deoplete.nvim: OK
- vim-superman: OK
- vim-obsession: OK
- gv.vim: OK
- vim-sneak: OK
- vim-colorschemes: OK
- close-buffers.vim: OK
- vim-gitgutter: OK
- vim-fahrenheit: OK
- HowMuch: OK
- vim-isort: OK
- vim-textobj-user: OK
- vim-toml: OK
- echodoc.vim: OK
- vim-fugitive: OK
- colorizer: OK
- yowish.vim: OK
- vim-test: OK
- vim-textobj-parameter: OK
- vim-speeddating: OK
- nvim-yarp: OK
- vim-liquid: OK
- FastFold: OK
- ale: OK
- .fzf: OK
- jedi-vim: OK
- fzf.vim: OK
- splitjoin.vim: OK
- delimitmate: OK
- vim-textobj-entire: OK
- vim-surround: OK
- julia-vim: OK
- inline_edit.vim: OK
```

</details>

**Comment by Shougo** [comment]
Oh, OK.  So I recommend for you to use `ddc.vim` instead.

https://github.com/Shougo/ddc.vim

**Comment by lukelbd** [comment]
Thanks for the help (and for all your work!). Is there a ddc-compatible alternative to `deoplete-jedi` (or maybe `deoplete-jedi` is compatible)?

**Comment by Shougo** [comment]
You should use LSP (vim-lsp or nvim-lsp) instead.
