### ISSUE TITLE
python2 compatibility

### ISSUE THREAD

**Issue by stu105502** [roxma/nvim-yarp#36]
Hey guys,

I had some trouble of getting your plugin work with python2. I'm quite sure that python2 shall be supported but I found a small issue. Your script 'pythonx/yarp.py' contains in the first line:
`
'from importlib.util import find_spec'
`
The problem is that 'importlib.util' was only introduced in python3 and every start with python2 will fail.  If I have a mistake on my side, I would appreciate, if you would help me so that I can run it properly. Thanks in advance!

Best regards,

Matthias

**Comment by Shougo** [comment]
I think you can create the PR for it.

**Comment by stu105502** [comment]
Okay, thank you very much. I'll take a look into it.
