### ISSUE TITLE
yarp can not take all data in windows, maybe. (^_^)

### ISSUE THREAD

**Issue by callmekohei** [roxma/nvim-yarp#5]
Hello! I'm `callmekohei`

Thank you your nvim-yarp, neovim-rpc!

### environment
I use yarp on deoplete.
```
Microsoft Windows [Version 10.0.16299.19]

C:\Users\callmekohei>vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  2 2017 12:54:54)
MS-Windows 32-bit console version
Included patches: 1-596
```
```
deoplete.nvim [master]$ gittree | head
* 	 3c38321 Tue Nov 7 08:57:54 2017 +0900 Fix #571 update FAQ section  (HEAD -> master, origin/master, origin/HEAD)

nvim-yarp [master]$ gittree | head
* 	 edb260a Wed Oct 25 14:23:34 2017 +0800 silent sleep to avoid the "Press ENTER or type command to continue" message  (HEAD -> master, origin/master, origin/HEAD)

vim-hug-neovim-rpc [master]$ gittree | head
* 	 0b8e70f Thu Nov 9 21:59:06 2017 +0800 add nvim_buf_line_count(buffer) method  (HEAD -> master, origin/master, origin/HEAD)
```

### problem
yarp can not take data in windows, maybe. 
```
(ideal)
List. aaa
      bbb
      ccc
      ddd

(real)
List. aaa
      bbb
```

### chart
```
deoplete ---> server(deopletefs) ---> deoplete
           
                                  ^
                                  |
                                  |
                                  |
                                this!!!
```

### maybe ...

`server(deopletefs) ---> deoplete` is super speed. So, this cause that yarp can't catch all data.

**Comment by roxma** [comment]
> server(deopletefs) ---> deoplete is super speed. So, this cause that yarp can't catch all data.

hmm... 

You could generate the log files of deopletefs to prove that the completion source is generating the expected result.

After that, use something like

```vim
let $NVIM_PYTHON_LOG_FILE="/tmp/nvim_log"
let $NVIM_PYTHON_LOG_LEVEL="DEBUG"
```

to generate log files so that you could monitor the traffic between deoplete and vim.

**Comment by callmekohei** [comment]
hmm...

It's  difficult for me. 

But I'll try it . (^_^)/

**Comment by callmekohei** [comment]
I done!

So, I generate logfile of deopletefs, deoplete and yarp.

It makes deopletefs a little slowly.

So, yarp can catch all data!

In other word, yarp can not catch all data if deopletefs is nomal mode.

### deoplete
it works well!
![screen shot 2017-11-13 at 18 17 13](https://user-images.githubusercontent.com/17691683/32718068-3bdc33e0-c89f-11e7-8b71-9ae1866f442d.png)

### deopletefs logfile
![screen shot 2017-11-13 at 18 17 24](https://user-images.githubusercontent.com/17691683/32718073-3f39cbec-c89f-11e7-857f-5e32e5e55759.png)

### rpc logfile
![screen shot 2017-11-13 at 18 17 32](https://user-images.githubusercontent.com/17691683/32718077-41c78228-c89f-11e7-8ba7-feeac63e533c.png)

### deoplete logfile
![screen shot 2017-11-13 at 18 17 49](https://user-images.githubusercontent.com/17691683/32718079-43e8da70-c89f-11e7-9c9a-e9fb4f4546f5.png)

**Comment by callmekohei** [comment]
Hi! 

I change deopletfs(server) to get slow 25ms.

So, it work done!

![untitled](https://user-images.githubusercontent.com/17691683/32723158-c7c93cda-c8af-11e7-9eda-5dc2a21f8b40.gif)
