### ISSUE TITLE
Question about Requirements for Vim 8

### ISSUE THREAD

**Issue by gilfuser** [roxma/nvim-yarp#7]
Hi. I'm sorry I'm making a question here, where I should report an issue. I couldn't find other communication channel.
I'm new to Vim, and even more to nvim-yarp. I'm here because it is requested for Neoplet.
I'm using Vim 8.
I can't understand in the Requirements, in the Read-Me, where should I evaluate this:
"g:python3_host_prog pointed to your python3 executable, or echo exepath('python3') is not empty." and what does it mean.

thank you in advance

bests,
Gil

**Comment by roxma** [comment]
`"g:python3_host_prog pointed to your python3 executable`

Means: `let g:python3_host_prog="/path/to/your/python3"` in your vimrc

means `:echo exepath('python3')`
